In [1]:
#imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import collections
import seaborn as sns
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import pandas as pd 
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline 

import gc
from datetime import datetime 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
#from catboost import CatBoostClassifier
#import lightgbm as lgb
#import xgboost as xgb


In [2]:
#reading data
data = pd.read_csv('creditproject.csv')
data.head()

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0   1      20000    2          2         1   24      2      2     -1     -1   
1   2     120000    2          2         2   26     -1      2      0      0   
2   3      90000    2          2         2   34      0      0      0      0   
3   4      50000    2          2         1   37      0      0      0      0   
4   5      50000    1          2         1   57     -1      0     -1      0   

              ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  \
0             ...                      0          0          0         0   
1             ...                   3272       3455       3261         0   
2             ...                  14331      14948      15549      1518   
3             ...                  28314      28959      29547      2000   
4             ...                  20940      19146      19131      2000   

   PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0       689         0         0         0         0   
1      1000      1000      1000         0      2000   
2      1500      1000      1000      1000      5000   
3      2019      1200      1100      1069      1000   
4     36681     10000      9000       689       679   

   default payment next month  
0                           1  
1                           1  
2                           0  
3                           0  
4                           0  

[5 rows x 25 columns]

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
ID                            30000 non-null int64
LIMIT_BAL                     30000 non-null int64
SEX                           30000 non-null int64
EDUCATION                     30000 non-null int64
MARRIAGE                      30000 non-null int64
AGE                           30000 non-null int64
PAY_0                         30000 non-null int64
PAY_2                         30000 non-null int64
PAY_3                         30000 non-null int64
PAY_4                         30000 non-null int64
PAY_5                         30000 non-null int64
PAY_6                         30000 non-null int64
BILL_AMT1                     30000 non-null int64
BILL_AMT2                     30000 non-null int64
BILL_AMT3                     30000 non-null int64
BILL_AMT4                     30000 non-null int64
BILL_AMT5                     30000 non-null int64
BILL_AMT6               

In [4]:
#Splitting data
categoric = data.iloc[:,[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23]]

Y = data.iloc[:,-1].values
Y.shape
categoric.shape

(30000, 23)

In [5]:
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(Y)
y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [6]:
sc = StandardScaler()
final_scaled = sc.fit_transform(categoric)

c:\users\saisr\appdata\local\programs\python\python36\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
c:\users\saisr\appdata\local\programs\python\python36\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [7]:
print(final_scaled)

[[-1.13672015  0.81016074  0.18582826 ... -0.30806256 -0.31413612
  -0.29338206]
 [-0.3659805   0.81016074  0.18582826 ... -0.24422965 -0.31413612
  -0.18087821]
 [-0.59720239  0.81016074  0.18582826 ... -0.24422965 -0.24868274
  -0.01212243]
 ...
 [-1.05964618 -1.23432296  0.18582826 ... -0.03996431 -0.18322937
  -0.11900109]
 [-0.67427636 -1.23432296  1.45111372 ... -0.18512036  3.15253642
  -0.19190359]
 [-0.90549825 -1.23432296  0.18582826 ... -0.24422965 -0.24868274
  -0.23713013]]


In [8]:
a=pd.DataFrame(final_scaled)
a.head()

0         1         2         3         4         5         6   \
0 -1.136720  0.810161  0.185828 -1.057295 -1.246020  1.794564  1.782348   
1 -0.365981  0.810161  0.185828  0.858557 -1.029047 -0.874991  1.782348   
2 -0.597202  0.810161  0.185828  0.858557 -0.161156  0.014861  0.111736   
3 -0.905498  0.810161  0.185828 -1.057295  0.164303  0.014861  0.111736   
4 -0.905498 -1.234323  0.185828 -1.057295  2.334029 -0.874991  0.111736   

         7         8         9     ...           13        14        15  \
0 -0.696663 -0.666599 -1.530046    ...    -0.667993 -0.672497 -0.663059   
1  0.138865  0.188746  0.234917    ...    -0.639254 -0.621636 -0.606229   
2  0.138865  0.188746  0.234917    ...    -0.482408 -0.449730 -0.417188   
3  0.138865  0.188746  0.234917    ...     0.032846 -0.232373 -0.186729   
4 -0.696663  0.188746  0.234917    ...    -0.161189 -0.346997 -0.348137   

         16        17        18        19        20        21        22  
0 -0.652724 -0.341942 -0.227086 -0.296801 -0.308063 -0.314136 -0.293382  
1 -0.597966 -0.341942 -0.213588 -0.240005 -0.244230 -0.314136 -0.180878  
2 -0.391630 -0.250292 -0.191887 -0.240005 -0.244230 -0.248683 -0.012122  
3 -0.156579 -0.221191 -0.169361 -0.228645 -0.237846 -0.244166 -0.237130  
4 -0.331482 -0.221191  1.335034  0.271165  0.266434 -0.269039 -0.255187  

[5 rows x 23 columns]

In [9]:
X_train_res, X_test, y_train_res, y_test = train_test_split(final_scaled, y, test_size=0.3, random_state=0)

In [10]:
#DT
dtclassifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
dtclassifier.fit(X_train_res,y_train_res)
y_pred = dtclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[5832, 1228],
       [1186,  754]], dtype=int64)

In [11]:
accuracy_score(y_test, y_pred)

0.7317777777777777

In [12]:
#lr
lrclassifier = LogisticRegression(random_state = 0)
lrclassifier.fit(X_train_res,y_train_res)
y_pred = lrclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

c:\users\saisr\appdata\local\programs\python\python36\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[6897,  163],
       [1493,  447]], dtype=int64)

In [13]:
accuracy_score(y_test, y_pred)

0.816

In [14]:
#knn
knnclassifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knnclassifier.fit(X_train_res,y_train_res)
y_pred = knnclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

array([[6451,  609],
       [1294,  646]], dtype=int64)

In [15]:
accuracy_score(y_test, y_pred)

0.7885555555555556

In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test, y_pred)

0.6233645337460939

In [ ]:
#svm
svmclassifier = SVC(kernel = 'linear', random_state = 0)
svmclassifier.fit(X_train_res,y_train_res)
y_pred = svmclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
#rf
rfclassifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rfclassifier.fit(X_train_res,y_train_res)
y_pred = rfclassifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

In [ ]:
accuracy_score(y_test, y_pred)

In [ ]:
import matplotlib.pyplot as plt; plt.rcdefaults()
import numpy as np
import matplotlib.pyplot as plt
 
objects = ('DECISION TREE ', 'LOG. REG.', 'KNN', 'SVM' , 'RAND. FOREST')
y_pos = np.arange(len(objects))
performance = [73.1,81.6,78.8,81.5,81.4]
 
plt.bar(y_pos, performance, align='center', alpha=1.0)
plt.xticks(y_pos, objects)
plt.ylabel('ACCURACY')
plt.title('ACCURACIES OF DIFFERENT CLASSIFICATION MODELS ')
 
plt.show()